### ISSUE TITLE
Investigate bug with beautifulsoup4 v4.6.2

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#213]
In #205 I pinned `beautitfulsoup ==4.6.0` because our tests fail badly on 4.6.2. See [this build](https://circleci.com/gh/edgi-govdata-archiving/web-monitoring-processing/289). We should investigate why; I took a quick look and it was not immediately clear.

**Comment by Mr0grog** [comment]
Taking a quick gander, it looks like this is related to our use of `formatter=None` when re-combining diffed HTML: https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/4e8a815cb4a73a7f90685e1c2e23688ddf2bf1df/web_monitoring/html_diff_render.py#L306-L316

(Note the comment about why that’s important.)

Looking at [the release notes](https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/NEWS.txt), there were definitely some changes to how formatters work in 4.6.1. Technically, [`formatter=None` is still documented as a supported setting](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#output-formatters), but it looks like that doesn’t actually work in practice — the failure stack trace shows BeautifulSoup trying to read an attribute from the formatter even though there isn’t one:

```
>           close = formatter.void_element_close_prefix or ''
E           AttributeError: 'NoneType' object has no attribute 'void_element_close_prefix'

venv/lib/python3.6/site-packages/bs4/element.py:1227: AttributeError
```

I think this is an upstream bug in Beautiful Soup. Need to create a minimal test case for them.

**Comment by Mr0grog** [comment]
Really similar to this bug: https://bugs.launchpad.net/beautifulsoup/

Need to see if that fix addressed it — it *looks* like it should have: https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/revision/474

**Comment by Mr0grog** [comment]
Fixed in #238.
